// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lglzpmqadzunisfbtxuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnbHpwbXFhZHp1bmlzZmJ0eHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTQyNjAsImV4cCI6MjA3MTQ3MDI2MH0.AoDyCpYI4eSwiGvlXwkYInJtXtqREgGU7TbmMdQ0TH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});